### ISSUE TITLE
Support for (x)HTML character entities in user input

### ISSUE THREAD

**Issue by cmrn** [klepas/votie#15]
Symbols such as `&`, `<`, `>`, etc. in user input are not converted to HTML character entities.

For example: the `&` glyph needs to be replaced by the HTML entity `&amp;` in the titles of presentations.

**Comment by klepas** [comment]
Ah, good point. We should also implement Smartypants while we’re at it. Thanks for raising this — will fix!

**Comment by RohanM** [comment]
This got fixed in the upgrade to Rails 3, which does this processing automatically.
