### ISSUE TITLE
Fix ‘Make Hack Void: Canberra Hackerspace’ talk slide URL link

### ISSUE THREAD

**Issue by klepas** [klepas/votie#18]
The submitter omitted `http://` and the URL now points to `http://votieapp.org/www.makehackvoid.com`. We need to provide labels and example content to guide user input when submitting their talks — see issue #17.

**Comment by klepas** [comment]
Discussed: aim to handle URLs really nicely (check for `www`, `http://`, … and automically do the right thing).

**Comment by RohanM** [comment]
Done - the field is initialised with "http://", and this is prepended on save if the url doesn't start with it.

**Comment by klepas** [comment]
Nice. Thanks. (:
