### ISSUE TITLE
Plain ol’ email address & password authentication

### ISSUE THREAD

**Issue by klepas** [klepas/votie#25]
Should we add this? Not sure — there was one guy at BCC2010 who didn’t use Twitter, and when I mentioned we were thinking of adding identi.ca and OpenID support he mentioned he didn’t use either of those either. Just a thought?

**Comment by RohanM** [comment]
Done! Pascal, on http://votieapp.org, your password is set to "changeme". You should be able to login with that and then change it on the "Update my details" page. There's a bit of CSS work to do on the user forms (sign up, sign in, edit details), could you have a look at that? Nothing too major, just field alignment and anything else you'd like to tweak.

Cheers,
Rohan

**Comment by klepas** [comment]
Sure. I’ve made an issue for it.
