### ISSUE TITLE
Remove the dev logins for RohanM and klepas and ensure login is available via secondary nav

### ISSUE THREAD

**Issue by klepas** [klepas/votie#5]
The markup and code for this is currently in `app/views/talks/index.html.haml`, and then implement login functionality via the the secondary nav (the top-bar).

**Comment by RohanM** [comment]
Done! You can still access them if needed with the following URL:

http://localhost:3000/users/login/dev?name=Rohan&twitter_name=RohanM

Insert your own name and twitter_name as desired.

**Comment by klepas** [comment]
Thanks. (:
